steps:
- name: "gcr.io/cloud-builders/go"
  args: ["install", "github.com/googlecloudplatform/golang-docker"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/your-app-name", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/your-app-name"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "app.yaml"]


