steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_DOCKER_IMAGE_REPO_NAME/$_DOCKER_IMAGE_NAME', '.']
# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_DOCKER_IMAGE_REPO_NAME/$_DOCKER_IMAGE_NAME']
# Create secret.yaml
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - "-c"
    - |
      cat << EOF >> app-secret.yaml
      BUCKET: $$BUCKET
      POSTGRES_HOST: '$$POSTGRES_HOST'
      POSTGRES_USER: $$POSTGRES_USER
      POSTGRES_DB: $$POSTGRES_DB
      POSTGRES_PASSWORD: $$POSTGRES_PASSWORD
      POSTGRES_PORT: '$$POSTGRES_PORT'
      INSTANCE_CONNECTION_NAME: '$$INSTANCE_CONNECTION_NAME'
      PRIVATE_IP: '$$PRIVATE_IP'
      EOF
  secretEnv: ['BUCKET', 'POSTGRES_HOST', 'POSTGRES_USER', 'POSTGRES_DB', 'POSTGRES_PASSWORD', 'POSTGRES_PORT', 'INSTANCE_CONNECTION_NAME', 'PRIVATE_IP']
# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'helloworld'
    - '--image'
    - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_DOCKER_IMAGE_REPO_NAME/$_DOCKER_IMAGE_NAME'
    - '--region'
    - '$_REGION'
    - '--env-vars-file'
    - './app-secret.yaml'
substitutions:
  _REGION: 'asia-northeast1'
  _DOCKER_IMAGE_REPO_NAME: 'go-sandbox'
  _DOCKER_IMAGE_NAME: 'todo:${SHORT_SHA}'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/BUCKET/versions/latest
    env: 'BUCKET'
  - versionName: projects/$PROJECT_NUMBER/secrets/POSTGRES_HOST/versions/latest
    env: 'POSTGRES_HOST'
  - versionName: projects/$PROJECT_NUMBER/secrets/POSTGRES_USER/versions/latest
    env: 'POSTGRES_USER'
  - versionName: projects/$PROJECT_NUMBER/secrets/POSTGRES_DB/versions/latest
    env: 'POSTGRES_DB'
  - versionName: projects/$PROJECT_NUMBER/secrets/POSTGRES_PASSWORD/versions/latest
    env: 'POSTGRES_PASSWORD'
  - versionName: projects/$PROJECT_NUMBER/secrets/POSTGRES_PORT/versions/latest
    env: 'POSTGRES_PORT'
  - versionName: projects/$PROJECT_NUMBER/secrets/INSTANCE_CONNECTION_NAME/versions/latest
    env: 'INSTANCE_CONNECTION_NAME'
  - versionName: projects/$PROJECT_NUMBER/secrets/PRIVATE_IP/versions/latest
    env: 'PRIVATE_IP'