steps:
# show substitutions
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "My custom environment variable: $_REGION, $_DOCKER_IMAGE_REPO_NAME, $_DOCKER_IMAGE_NAME"
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_DOCKER_IMAGE_REPO_NAME/$_DOCKER_IMAGE_NAME', '.']
# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_DOCKER_IMAGE_REPO_NAME/$_DOCKER_IMAGE_NAME']
# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'helloworld-${SHORT_SHA}',
         '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_DOCKER_IMAGE_REPO_NAME/$_DOCKER_IMAGE_NAME',
         '--region', '$_REGION', '--platform', 'managed']
substitutions:
  _REGION: 'asia-northeast1'
  _DOCKER_IMAGE_REPO_NAME: 'go-sandbox'
  _DOCKER_IMAGE_NAME: 'todo:$SHORT_SHA'