// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"sync"
)

// Ensure, that ExternalAPIClientMock does implement ExternalAPIClient.
// If this is not the case, regenerate this file with moq.
var _ ExternalAPIClient = &ExternalAPIClientMock{}

// ExternalAPIClientMock is a mock implementation of ExternalAPIClient.
//
//	func TestSomethingThatUsesExternalAPIClient(t *testing.T) {
//
//		// make and configure a mocked ExternalAPIClient
//		mockedExternalAPIClient := &ExternalAPIClientMock{
//			FetchUserFunc: func(id int) (*User, error) {
//				panic("mock out the FetchUser method")
//			},
//			UpdateUserFunc: func(user *User) error {
//				panic("mock out the UpdateUser method")
//			},
//		}
//
//		// use mockedExternalAPIClient in code that requires ExternalAPIClient
//		// and then make assertions.
//
//	}
type ExternalAPIClientMock struct {
	// FetchUserFunc mocks the FetchUser method.
	FetchUserFunc func(id int) (*User, error)

	// UpdateUserFunc mocks the UpdateUser method.
	UpdateUserFunc func(user *User) error

	// calls tracks calls to the methods.
	calls struct {
		// FetchUser holds details about calls to the FetchUser method.
		FetchUser []struct {
			// ID is the id argument value.
			ID int
		}
		// UpdateUser holds details about calls to the UpdateUser method.
		UpdateUser []struct {
			// User is the user argument value.
			User *User
		}
	}
	lockFetchUser  sync.RWMutex
	lockUpdateUser sync.RWMutex
}

// FetchUser calls FetchUserFunc.
func (mock *ExternalAPIClientMock) FetchUser(id int) (*User, error) {
	if mock.FetchUserFunc == nil {
		panic("ExternalAPIClientMock.FetchUserFunc: method is nil but ExternalAPIClient.FetchUser was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockFetchUser.Lock()
	mock.calls.FetchUser = append(mock.calls.FetchUser, callInfo)
	mock.lockFetchUser.Unlock()
	return mock.FetchUserFunc(id)
}

// FetchUserCalls gets all the calls that were made to FetchUser.
// Check the length with:
//
//	len(mockedExternalAPIClient.FetchUserCalls())
func (mock *ExternalAPIClientMock) FetchUserCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockFetchUser.RLock()
	calls = mock.calls.FetchUser
	mock.lockFetchUser.RUnlock()
	return calls
}

// UpdateUser calls UpdateUserFunc.
func (mock *ExternalAPIClientMock) UpdateUser(user *User) error {
	if mock.UpdateUserFunc == nil {
		panic("ExternalAPIClientMock.UpdateUserFunc: method is nil but ExternalAPIClient.UpdateUser was just called")
	}
	callInfo := struct {
		User *User
	}{
		User: user,
	}
	mock.lockUpdateUser.Lock()
	mock.calls.UpdateUser = append(mock.calls.UpdateUser, callInfo)
	mock.lockUpdateUser.Unlock()
	return mock.UpdateUserFunc(user)
}

// UpdateUserCalls gets all the calls that were made to UpdateUser.
// Check the length with:
//
//	len(mockedExternalAPIClient.UpdateUserCalls())
func (mock *ExternalAPIClientMock) UpdateUserCalls() []struct {
	User *User
} {
	var calls []struct {
		User *User
	}
	mock.lockUpdateUser.RLock()
	calls = mock.calls.UpdateUser
	mock.lockUpdateUser.RUnlock()
	return calls
}
